### PR TITLE
counting args correctly

### PR DESCRIPTION
**Pull request by peleghila**
Still counting arrows, but correctly this time.

### CODE REVIEW

**Comment by michaelbjames** [comment]
Seems there's a bug:
`getArgCount("a -> (b -> c)") = 1` but this function has two arguments for the purposes of hoogle plus.

I'm most concerned about `Int -> (a -> a) -> a -> a`, which we have in our notes as `Int -> (a -> a) -> (a -> a)`. That said, this does property count that HOF, so it's deffo an improvement on the base version.

I suppose we can guide the user not to put extra parens in.

**Comment by peleghila** [comment]
Wait... why? (I can maybe fix them, but I don't understand the expected result.)

**Comment by michaelbjames** [comment]
Since arrow is right-associative, `a -> b` is the same as `a -> (b)`, So `a -> b -> c` is the same as `a -> (b -> c)`. Read out, "a function that takes an `a` and produces a function that takes a `b` and produces a `c`, would be written most clearly as `a -> (b -> c)`. But in Haskell, all functions are curried and can be partially applied.

Said slightly differently:
```
foo :: a -> b -> c

let foo1 = (foo a)
foo1 :: b -> c

let foo2 = foo1 b
foo2 :: c

foo :: a -> (b -> c)
```

Does that answer your question?

**Comment by peleghila** [comment]
Yes. Followup: does that mean we expect anything that is not parentheses in the middle to be treated as individual args, then?

**Comment by michaelbjames** [comment]
Correct. It's parens that build up on the end that are redundant. If you can't think up a clever algorithm, then your current PR is still the necessary improvement over my first hacky implementation to do the pilot (and probably also the study)

**Comment by peleghila** [comment]
Cool. I'll give it another try a little later.

**Comment by peleghila** [comment]
Try this. It's not the best way ever to do it, but I think it'll hold.

**Comment by michaelbjames** [comment]
Thanks for doing this Hila!

**Pull request merged**
